from django.db import models

class DatasetEntry(models.Model):
    date = models.DateField()
    notes = models.TextField(blank=True)
    moca = models.CharField(max_length=100, blank=True)
    exercise = models.CharField(max_length=100, blank=True)
    b = models.CharField(max_length=100, blank=True)
    biosense = models.CharField(max_length=100, blank=True)
    breakfast_ace = models.IntegerField(null=True, blank=True)
    lunch_ace = models.IntegerField(null=True, blank=True)
    dinner_ace = models.IntegerField(null=True, blank=True)
    meals = models.CharField(max_length=100, blank=True)
    breakfast = models.CharField(max_length=100, blank=True)
    lunch = models.CharField(max_length=100, blank=True)
    dinner = models.CharField(max_length=100, blank=True)
    supplements = models.CharField(max_length=100, blank=True)
    omega_3 = models.CharField(max_length=100, blank=True)
    iron = models.CharField(max_length=100, blank=True)
    b1 = models.CharField(max_length=100, blank=True)
    d = models.CharField(max_length=100, blank=True)
    synapsin = models.CharField(max_length=100, blank=True)
    hormones = models.CharField(max_length=100, blank=True)
    thyroid = models.CharField(max_length=100, blank=True)
    estradiol = models.CharField(max_length=100, blank=True)
    progesterone = models.CharField(max_length=100, blank=True)
    mycotoxin_binders = models.CharField(max_length=100, blank=True)
    sac_b = models.CharField(max_length=100, blank=True)
    nac = models.CharField(max_length=100, blank=True)
    charcoal = models.CharField(max_length=100, blank=True)
    bentonite_clay = models.CharField(max_length=100, blank=True)
    optifibre = models.CharField(max_length=100, blank=True)
    interfase_plus = models.CharField(max_length=100, blank=True)
    welchol = models.CharField(max_length=100, blank=True)
    itraconazole = models.CharField(max_length=100, blank=True)
    nystain_oral = models.CharField(max_length=100, blank=True)
    nystatin_nasal = models.CharField(max_length=100, blank=True)
    medication = models.CharField(max_length=100, blank=True)
    code_gg = models.CharField(max_length=100, blank=True)
    code_mm = models.CharField(max_length=100, blank=True)
    code_zz = models.CharField(max_length=100, blank=True)
    code_ss = models.CharField(max_length=100, blank=True)
    fsm_protocol = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return str(self.date)